name: 'build-test'
on: # rebuild any PRs and main branch changes
  release:
    types: [published]
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
      - name: Build script
        run: npm run build
      - name: Test code
        run: npm run test

